variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERM: linux
  GIT_STRATEGY: fetch

stages:
  - build
  - deploy

pdf:
  stage: build
  script:
    - make all
  tags:
    - generic
  artifacts:
    paths:
      - cours/introduction.pdf
      - ds/partiel-2013.pdf
      - ds/partiel-2014.pdf
      - ds/partiel-2018.pdf
      - ds/correction-partiel-2013.pdf
      - ds/correction-partiel-2014.pdf
      - ds/correction-partiel-2018.pdf
      - td/1/td1.pdf
      - td/2/td2.pdf
      - td/3/td3.pdf
      - td/1/correction-td1.pdf
      - td/2/correction-td2.pdf
      - td/3/correction-td3.pdf
    expire_in: 1 day

web:
  stage: deploy
  only:
    - master@University/growth
  tags:
    - restricted
  dependencies:
    - pdf
  script:
    - cp cours/introduction.pdf /home/www/le-mans.adjemian.eu/croissance/cours/introduction.pdf
    - ds/partiel-2013.pdf /home/www/le-mans.adjemian.eu/croissance/ds/partiel-2013.pdf
    - ds/partiel-2014.pdf /home/www/le-mans.adjemian.eu/croissance/ds/partiel-2014.pdf
    - ds/partiel-2018.pdf /home/www/le-mans.adjemian.eu/croissance/ds/partiel-2018.pdf
    - ds/correction-partiel-2013.pdf /home/www/le-mans.adjemian.eu/croissance/ds/correction-partiel-2013.pdf
    - ds/correction-partiel-2014.pdf /home/www/le-mans.adjemian.eu/croissance/ds/correction-partiel-2014.pdf
    - ds/correction-partiel-2018.pdf /home/www/le-mans.adjemian.eu/croissance/ds/correction-partiel-2018.pdf
    - cp -r td/1/td1.pdf /home/www/le-mans.adjemian.eu/croissance/td/1/td1.pdf
    - cp -r td/2/td2.pdf /home/www/le-mans.adjemian.eu/croissance/td/2/td2.pdf
    - cp -r td/3/td3.pdf /home/www/le-mans.adjemian.eu/croissance/td/3/td3.pdf
    - cp -r td/1/correction-td1.pdf /home/www/le-mans.adjemian.eu/croissance/td/1/correction-td1.pdf
    - cp -r td/2/correction-td2.pdf /home/www/le-mans.adjemian.eu/croissance/td/2/correction-td2.pdf
    - cp -r td/3/correction-td3.pdf /home/www/le-mans.adjemian.eu/croissance/td/3/correction-td3.pdf
